// countries.js
const countries = {
  '🇺🇸': 'United States',
  '🇨🇦': 'Canada',
  '🇲🇽': 'Mexico',
  '🇧🇷': 'Brazil',
  '🇬🇧': 'United Kingdom',
  ':england:': 'England',
  ':scotland': 'Scotland',
  ':wales:': 'Wales',
  '🇫🇷': 'France',
  '🇩🇪': 'Germany',
  '🇳🇱': 'Netherlands',
  '🇸🇪': 'Sweden',
  '🇳🇴': 'Norway',
  '🇩🇰': 'Denmark',
  '🇫🇮': 'Finland',
  '🇪🇸': 'Spain',
  '🇮🇹': 'Italy',
  '🇵🇱': 'Poland',
  '🇨🇿': 'Czech Republic',
  '🇭🇺': 'Hungary',
  '🇷🇴': 'Romania',
  '🇷🇺': 'Russia',
  '🇺🇦': 'Ukraine',
  '🇬🇷': 'Greece',
  '🇹🇷': 'Turkey',
  '🇮🇱': 'Israel',
  '🇮🇳': 'India',
  '🇨🇳': 'China',
  '🇯🇵': 'Japan',
  '🇰🇷': 'South Korea',
  '🇸🇬': 'Singapore',
  '🇹🇭': 'Thailand',
  '🇻🇳': 'Vietnam',
  '🇮🇩': 'Indonesia',
  '🇦🇺': 'Australia',
  '🇳🇿': 'New Zealand',
  '🇿🇦': 'South Africa',
  '🇪🇬': 'Egypt',
  '🇲🇦': 'Morocco',
  '🇩🇿': 'Algeria',
  '🇳🇬': 'Nigeria',
  '🇰🇪': 'Kenya',
  '🇧🇪': 'Belgium',
  '🇨🇭': 'Switzerland',
  '🇦🇹': 'Austria',
  '🇮🇪': 'Ireland',
  '🇵🇹': 'Portugal',
  '🇸🇰': 'Slovakia',
  '🇸🇮': 'Slovenia',
  '🇭🇷': 'Croatia',
  '🇧🇬': 'Bulgaria',
  '🇨🇷': 'Costa Rica',
  '🇨🇱': 'Chile',
  '🇦🇷': 'Argentina',
  '🇨🇴': 'Colombia',
  '🇵🇪': 'Peru',
  '🇻🇪': 'Venezuela',
  '🇨🇺': 'Cuba',
  '🇯🇲': 'Jamaica',
  '🇸🇦': 'Saudi Arabia',
  '🇦🇪': 'United Arab Emirates',
  '🇶🇦': 'Qatar',
  '🇧🇭': 'Bahrain',
  '🇰🇼': 'Kuwait',
  '🇴🇲': 'Oman',
  '🇮🇷': 'Iran',
  '🇮🇶': 'Iraq',
  '🇱🇧': 'Lebanon',
  '🇯🇴': 'Jordan',
  '🇵🇰': 'Pakistan',
  '🇧🇩': 'Bangladesh',
  '🇱🇰': 'Sri Lanka',
  '🇳🇵': 'Nepal',
  '🇵🇭': 'Philippines',
  '🇲🇾': 'Malaysia',
  '🇭🇰': 'Hong Kong',
  '🇹🇼': 'Taiwan',
  '🇲🇳': 'Mongolia',
  '🇰🇭': 'Cambodia',
  '🇱🇦': 'Laos',
  '🇧🇳': 'Brunei',
  '🇲🇲': 'Myanmar',
  '🇵🇱': 'Poland',
  '🇨🇾': 'Cyprus',
  '🇪🇪': 'Estonia',
  '🇱🇻': 'Latvia',
  '🇱🇹': 'Lithuania',
  '🇧🇾': 'Belarus',
  '🇷🇸': 'Serbia',
  '🇧🇦': 'Bosnia and Herzegovina',
  '🇲🇰': 'North Macedonia',
  '🇦🇱': 'Albania',
  '🇬🇪': 'Georgia',
  '🇦🇲': 'Armenia',
  '🇦🇿': 'Azerbaijan',
};

const aliases = {
  ':england:': '🇬🇧', // England → treat as UK
  ':scotland:': '🇬🇧', // Scotland → treat as UK
  ':wales:': '🇬🇧', // Wales → treat as UK
};

// Merge aliases into the main mapping
for (const [alias, target] of Object.entries(aliases)) {
  if (countries[target]) countries[alias] = countries[target];
}

module.exports = { countries };
