// config/ecoConfig.js
module.exports = {
  resources: [
    { name: "wood", emoji: "🪵", min: 1, max: 4 },
    { name: "stone", emoji: "🪨", min: 1, max: 3 },
    { name: "clay", emoji: "🧱", min: 1, max: 3 },
    { name: "leaves", emoji: "🍃", min: 2, max: 5 },
    { name: "water", emoji: "💧", min: 1, max: 4 },
    { name: "fiber", emoji: "🧶", min: 1, max: 2 },
    { name: "soil", emoji: "🌱", min: 1, max: 3 },
    { name: "herbs", emoji: "🌿", min: 1, max: 2 },
  ],

  // 🌾 Crafting recipes
  recipes: {
    plank: { emoji: "🪚", inputs: { wood: 3 }, output: { plank: 1 }, xp: 8 },
    brick: { emoji: "🧱", inputs: { clay: 3 }, output: { brick: 1 }, xp: 8 },
    rope: { emoji: "🪢", inputs: { fiber: 2 }, output: { rope: 1 }, xp: 8 },
    bottle: { emoji: "🍾", inputs: { sand: 3 }, output: { bottle: 1 }, xp: 10 },
    potion: {
      emoji: "🧪",
      inputs: { herbs: 2, water: 1 },
      output: { potion: 1 },
      xp: 12,
    },
    torch: {
      emoji: "🔥",
      inputs: { wood: 1, rope: 1 },
      output: { torch: 1 },
      xp: 10,
    },
    brick_wall: {
      emoji: "🏗️",
      inputs: { brick: 3, plank: 1 },
      output: { brick_wall: 1 },
      xp: 14,
    },
    herbal_mix: {
      emoji: "🌿✨",
      inputs: { herbs: 3 },
      output: { herbal_mix: 1 },
      xp: 10,
    },
    honey_balm: {
      emoji: "🧴",
      inputs: { herbal_mix: 1, water: 1 },
      output: { honey_balm: 1 },
      xp: 15,
    },
    charm: {
      emoji: "🧿",
      inputs: { rope: 1, herbs: 1 },
      output: { charm: 1 },
      xp: 10,
    },
    crystal: {
      emoji: "🔮",
      inputs: { stone: 5 },
      output: { crystal: 1 },
      xp: 20,
    },
    glass: {
      emoji: "🔹",
      inputs: { sand: 2, water: 1 },
      output: { glass: 1 },
      xp: 15,
    },
    steel: {
      emoji: "⚙️",
      inputs: { stone: 5, water: 1 },
      output: { steel: 1 },
      xp: 25,
    },
    power_core: {
      emoji: "💠",
      inputs: { crystal: 1, steel: 1 },
      output: { power_core: 1 },
      xp: 35,
    },
    arcane_scroll: {
      emoji: "📜✨",
      inputs: { herbal_mix: 1, crystal: 1 },
      output: { arcane_scroll: 1 },
      xp: 30,
    },
    solar_panel: {
      emoji: "🔆",
      inputs: { glass: 3, steel: 2 },
      output: { solar_panel: 1 },
      xp: 40,
    },
    garden_seed: {
      emoji: "🌾",
      inputs: { soil: 2, water: 1 },
      output: { garden_seed: 1 },
      xp: 10,
    },
    statue: {
      emoji: "🗿",
      inputs: { stone: 10 },
      output: { statue: 1 },
      xp: 40,
    },
    herbal_potion: {
      emoji: "🧪✨",
      inputs: { herbs: 2, potion: 1 },
      output: { herbal_potion: 1 },
      xp: 20,
    },
    sacred_blend: {
      emoji: "🌿💫",
      inputs: { herbal_mix: 2, crystal: 1 },
      output: { sacred_blend: 1 },
      xp: 35,
    },
    sunflower_seed_pack: {
      emoji: "🌻🌰",
      inputs: { sunflower: 2 },
      output: { sunflower_seed: 1 },
      xp: 6,
    },
    pumpkin_seed_pack: {
      emoji: "🎃🌰",
      inputs: { pumpkin: 1 },
      output: { pumpkin_seed: 1 },
      xp: 8,
    },
    lavender_seed_pack: {
      emoji: "💜🌰",
      inputs: { lavender: 3 },
      output: { lavender_seed: 1 },
      xp: 8,
    },
    berry_seed_pack: {
      emoji: "🫐🌰",
      inputs: { blueberries: 3 },
      output: { blueberry_seed: 1 },
      xp: 8,
    },
    cactus_seed_pack: {
      emoji: "🌵🌰",
      inputs: { cactus: 1 },
      output: { cactus_seed: 1 },
      xp: 10,
    },
    lotus_seed_pack: {
      emoji: "🌸🌰",
      inputs: { lotus_bloom: 2 },
      output: { lotus_seed: 1 },
      xp: 10,
    },
    bamboo_seed_bundle: {
      emoji: "🎋🌰",
      inputs: { bamboo: 3 },
      output: { bamboo_seed: 1 },
      xp: 10,
    },
    tea_seed_bundle: {
      emoji: "🍃🌰",
      inputs: { tea_leaves: 4 },
      output: { tea_leaf_seed: 1 },
      xp: 8,
    },
    strawberry_seed_pack: {
      emoji: "🍓🌰",
      inputs: { strawberries: 3 },
      output: { strawberry_seed: 1 },
      xp: 8,
    },
    tomato_seed_pack: {
      emoji: "🍅🌰",
      inputs: { tomatoes: 3 },
      output: { tomato_seed: 1 },
      xp: 8,
    },
    carrot_seed_pack: {
      emoji: "🥕🌰",
      inputs: { carrots: 3 },
      output: { carrot_seed: 1 },
      xp: 7,
    },
    potato_seed_pack: {
      emoji: "🥔🌰",
      inputs: { potatoes: 3 },
      output: { potato_seed: 1 },
      xp: 7,
    },
    corn_seed_pack: {
      emoji: "🌽🌰",
      inputs: { corn: 2 },
      output: { corn_seed: 1 },
      xp: 8,
    },
    chili_seed_pack: {
      emoji: "🌶️🌰",
      inputs: { chili_peppers: 3 },
      output: { chili_seed: 1 },
      xp: 8,
    },
    rice_seed_pack: {
      emoji: "🍚🌰",
      inputs: { rice: 3 },
      output: { rice_seed: 1 },
      xp: 8,
    },
    mint_seed_pack: {
      emoji: "🌿🌰",
      inputs: { mint_leaves: 3 },
      output: { mint_seed: 1 },
      xp: 7,
    },
    coffee_seed_pack: {
      emoji: "☕🌰",
      inputs: { coffee_beans: 3 },
      output: { coffee_seed: 1 },
      xp: 10,
    },
    cocoa_seed_pack: {
      emoji: "🍫🌰",
      inputs: { cocoa_beans: 3 },
      output: { cocoa_seed: 1 },
      xp: 10,
    },
    berry_tart: {
      emoji: "🥧",
      inputs: { strawberries: 2, blueberries: 3, honey_balm: 1 },
      output: { berry_tart: 1 },
      xp: 18,
    },
    sunrise_smoothie: {
      emoji: "🥤",
      inputs: { strawberries: 2, sunflower: 1, mint_leaves: 2 },
      output: { sunrise_smoothie: 1 },
      xp: 16,
    },
    veggie_stew: {
      emoji: "🍲",
      inputs: { potatoes: 2, carrots: 2, tomatoes: 2, herbs: 1 },
      output: { veggie_stew: 1 },
      xp: 20,
    },
    spicy_salsa: {
      emoji: "🌶️",
      inputs: { tomatoes: 2, chili_peppers: 3, herbs: 1 },
      output: { spicy_salsa: 1 },
      xp: 16,
    },
    herbal_tea: {
      emoji: "🍵",
      inputs: { tea_leaves: 3, mint_leaves: 2, honey_balm: 1 },
      output: { herbal_tea: 2 },
      xp: 15,
    },
    rice_bowl: {
      emoji: "🍚",
      inputs: { rice: 3, bamboo: 1, carrots: 1 },
      output: { rice_bowl: 1 },
      xp: 14,
    },
    cocoa_drink: {
      emoji: "🍫",
      inputs: { cocoa_beans: 2, honey_balm: 1, water: 1 },
      output: { cocoa_drink: 1 },
      xp: 18,
    },
    brewed_coffee: {
      emoji: "☕",
      inputs: { coffee_beans: 2, water: 1 },
      output: { brewed_coffee: 1 },
      xp: 12,
    },
  },

  // 🏪 Store prices
  store: {
   prices: {
      wood: 3,
      stone: 4,
      clay: 5,
      herbs: 6,
      sunflower: 5,
      pumpkin: 9,
      lavender: 7,
      blueberries: 8,
      cactus: 12,
      lotus_bloom: 14,
      bamboo: 9,
      tea_leaves: 8,
      strawberries: 9,
      tomatoes: 7,
      carrots: 6,
      potatoes: 6,
      corn: 8,
      coffee_beans: 10,
      chili_peppers: 9,
      rice: 7,
      mint_leaves: 5,
      cocoa_beans: 11,
      sunflower_seed: 12,
      pumpkin_seed: 18,
      lavender_seed: 14,
      blueberry_seed: 16,
      cactus_seed: 22,
      lotus_seed: 24,
      bamboo_seed: 25,
      tea_leaf_seed: 15,
      strawberry_seed: 14,
      tomato_seed: 13,
      carrot_seed: 9,
      potato_seed: 11,
      corn_seed: 15,
      coffee_seed: 22,
      chili_seed: 15,
      rice_seed: 13,
      mint_seed: 8,
      cocoa_seed: 23,
    },
  },

  // inside module.exports
  buildings: {
    garden: {
      name: "Community Garden",
      emoji: "🌿",
      cost: { soil: 20, water: 10, wood: 10 },
      reward: { calm: 10, xp: 40 },
      unlocks: ["garden_seed", "herbal_mix"],
    },
    sauna: {
      name: "Nature Sauna",
      emoji: "🔥",
      cost: { wood: 25, stone: 15, water: 10 },
      reward: { calm: 15, xp: 60 },
      unlocks: ["honey_balm", "torch"],
    },
    workshop: {
      name: "Village Workshop",
      emoji: "🛠️",
      cost: { wood: 30, stone: 20, plank: 10 },
      reward: { calm: 10, xp: 70 },
      unlocks: ["steel", "glass", "power_core"],
    },
    temple: {
      name: "Harmony Temple",
      emoji: "🏛️",
      cost: { brick: 50, crystal: 5, sacred_blend: 2 },
      reward: { calm: 25, xp: 120 },
      unlocks: ["sacred_blend", "arcane_scroll"],
    },
    treehouse: {
      name: "Skyview Treehouse",
      emoji: "🌲",
      cost: { wood: 40, rope: 10, plank: 15 },
      reward: { calm: 12, xp: 65 },
      unlocks: ["torch", "rope"],
    },
    library: {
      name: "Wisdom Library",
      emoji: "📚",
      cost: { wood: 35, brick: 20, glass: 10 },
      reward: { calm: 18, xp: 85 },
      unlocks: ["arcane_scroll", "charm"],
    },
    bakery: {
      name: "Sunrise Bakery",
      emoji: "🥐",
      cost: { wood: 25, water: 15, herbs: 10 },
      reward: { calm: 8, xp: 55 },
      unlocks: ["honey_balm"],
    },
    market: {
      name: "Village Market",
      emoji: "🛒",
      cost: { wood: 30, stone: 25, plank: 10 },
      reward: { calm: 14, xp: 75 },
      unlocks: ["glass", "steel"],
    },
    greenhouse: {
      name: "Crystal Greenhouse",
      emoji: "🏡",
      cost: { glass: 20, water: 15, soil: 25 },
      reward: { calm: 20, xp: 95 },
      unlocks: ["garden_seed", "herbal_potion"],
    },
    observatory: {
      name: "Star Observatory",
      emoji: "🔭",
      cost: { steel: 12, glass: 18, crystal: 4 },
      reward: { calm: 22, xp: 110 },
      unlocks: ["crystal", "power_core"],
    },
    healing_springs: {
      name: "Healing Springs",
      emoji: "💧",
      cost: { water: 40, stone: 20, herbs: 15 },
      reward: { calm: 28, xp: 100 },
      unlocks: ["potion", "herbal_potion"],
    },
    art_studio: {
      name: "Artisans' Studio",
      emoji: "🎨",
      cost: { wood: 20, clay: 20, fiber: 10 },
      reward: { calm: 16, xp: 70 },
      unlocks: ["charm", "statue"],
    },
    communal_kitchen: {
      name: "Communal Kitchen",
      emoji: "🍲",
      cost: { wood: 28, water: 12, herbs: 12 },
      reward: { calm: 15, xp: 60 },
      unlocks: ["honey_balm", "garden_seed"],
    },
    solar_farm: {
      name: "Solar Farm",
      emoji: "🔆",
      cost: { solar_panel: 8, steel: 10, glass: 12 },
      reward: { calm: 24, xp: 120 },
      unlocks: ["solar_panel", "power_core"],
    },
    beekeepers_lodge: {
      name: "Beekeepers' Lodge",
      emoji: "🐝",
      cost: { wood: 30, herbal_mix: 10, garden_seed: 6 },
      reward: { calm: 18, xp: 80 },
      unlocks: ["honey_balm", "potion"],
    },
    meditation_glade: {
      name: "Meditation Glade",
      emoji: "🧘",
      cost: { soil: 15, herbs: 15, crystal: 2 },
      reward: { calm: 30, xp: 90 },
      unlocks: ["sacred_blend"],
    },
    community_center: {
      name: "Community Center",
      emoji: "🏫",
      cost: { brick: 40, wood: 35, glass: 10 },
      reward: { calm: 20, xp: 105 },
      unlocks: ["steel", "glass", "arcane_scroll"],
    },
    aquaponics_bay: {
      name: "Aquaponics Bay",
      emoji: "🐟",
      cost: { water: 35, soil: 20, solar_panel: 4 },
      reward: { calm: 26, xp: 115 },
      unlocks: ["garden_seed", "glass"],
    },
    stone_circle: {
      name: "Stone Circle",
      emoji: "🪨",
      cost: { stone: 60, crystal: 3, sacred_blend: 1 },
      reward: { calm: 32, xp: 130 },
      unlocks: ["crystal", "sacred_blend"],
    },
    harbor: {
      name: "River Harbor",
      emoji: "⚓",
      cost: { wood: 45, stone: 35, rope: 10 },
      reward: { calm: 18, xp: 100 },
      unlocks: ["glass", "steel"],
    },
    festival_stage: {
      name: "Festival Stage",
      emoji: "🎪",
      cost: { wood: 35, fiber: 12, torch: 6 },
      reward: { calm: 22, xp: 90 },
      unlocks: ["torch", "charm"],
    },
    skybridge: {
      name: "Skybridge Walkway",
      emoji: "🌉",
      cost: { plank: 25, steel: 8, rope: 12 },
      reward: { calm: 20, xp: 105 },
      unlocks: ["steel", "power_core"],
    },
  },

  xpPerGather: 5,
  xpPerRelax: 5,
  calmPerRelax: 5,
};
